### ISSUE TITLE
1 bp features are not displayed

### ISSUE THREAD

**Issue by ClovisNorroy** [stothard-group/cgview-js#3]
Hi,
I am currently trying to display Single Nucleotide Polymorphisms but it doesn't seems currently possible to display features of less than 2 bp.
Furthermore, labels for 1 bp features are displayed but placed between 2 bp on the backbone, making it impossible to know which  nucleotide is targeted.
![image](https://user-images.githubusercontent.com/31315324/173380871-786904fe-ffb7-4b65-b8ba-50d58f67af90.png)

**Comment by ClovisNorroy** [comment]
It seems that 1 bp features are displayed (in a confusing way) with the arrow decorator only.
![image](https://user-images.githubusercontent.com/31315324/173390236-a90bb620-464f-4f7d-86e5-b2818861bf07.png)
The issue can be replicated on Proksee.

**Comment by sciguy** [comment]
The 1 bp issue is fixed. Features are now drawn from start-0.5bp to stop+0.5bp. The labels are also properly placed. 

The fix is available in version 1.3.0 (cf94943516282546b13e20773406ff5520a63b26)

![cgview_single_base_features](https://user-images.githubusercontent.com/211027/175655709-0d01923c-96aa-44c9-8fbf-a8d87b6f61b4.png)
